=== laputafish/yoovapi55/storage/forms/ir56m.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="IR56M">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Section">  <!-- Section -->
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:length value="3" />
                            <xs:pattern value="[0-9a-zA-Z]*" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ERN">  <!-- Payer's ERN -->
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1" />
                            <xs:maxLength value="8" />
                            <xs:pattern value="[0-9]*" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="AssYr">  <!-- Assessment Year of IR56M -->
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:length value="4" />
                            <xs:pattern value="[0-9]*" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="SubDate">  <!-- Submission Date -->
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:length value="8" />
                            <xs:pattern value="[0-9]*" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="PayerName">  <!-- Payer’s Name -->
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1" />
                            <xs:maxLength value="70" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Designation">  <!-- Designation -->
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="25" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="NoRecordBatch">  <!-- No. of Records in Batch -->
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1" />
                            <xs:maxLength value="5" />
                            <xs:pattern value="[0-9]*" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="TotIncomeBatch">  <!-- Total Income in Batch -->
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1" />
                            <xs:maxLength value="11" />
                            <xs:pattern value="[0-9]*" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Recipient" minOccurs="1" maxOccurs="unbounded">  <!-- Recipient’s IR56M record -->
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SheetNo">  <!-- Sheet No -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1" />
                                        <xs:maxLength value="6" />
                                        <xs:pattern value="[0-9]*" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ComRecNameEng">  <!-- Company Recipient’s name in English -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="70" />
                                        <xs:pattern value="[A-Z a-z0-9!#$%&amp;\*\(\)_\+\-=\\:&quot;;&apos;&lt;&gt;?,\./@]*" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ComRecNameChi">  <!-- Company Recipient’s name in Chinese -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="35" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ComRecBRN">  <!-- Company Recipient’s BRN -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="8" />
                                        <xs:pattern value="[0-9]*" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>                                                                                                               
                            <xs:element name="HKID" default="AA000000A">  <!-- Individual Recipient’s HKID with Check Digit -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="9" />
                                        <xs:pattern value="[A-Z a-z]{0,1}[A-Za-z]{1}[0-9]{6}[Aa0-9]{0,1}" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NameInEnglish">  <!-- Individual Recipient’s Full Name in English -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="27" />
                                        <xs:pattern value="[A-Z a-z0-9!#$%&amp;\*\(\)_\+\-=\\:&quot;;&apos;&lt;&gt;?,\./@]*" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NameInChinese">  <!-- Individual Recipient’s Full Name in Chinese -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="25" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Sex">  <!-- Individual Recipient’s Sex -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="M" />
                                        <xs:enumeration value="F" />
                                        <xs:enumeration value="m" />
                                        <xs:enumeration value="f" />
                                        <xs:enumeration value="" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MaritalStatus">  <!-- Individual Recipient’s Marital Status -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="1" />
                                        <xs:enumeration value="2" />
                                        <xs:enumeration value="" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="SpouseName">  <!-- Individual Spouse’s Name -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="SpouseHKID">  <!-- Individual Spouse’s HKID with Check Digit -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="9" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="SpousePpNum">  <!-- Spouse’s Passport No. and Country of Issue -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="40" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="PosAddr">  <!-- Recipient’s Correspondence Address -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="90" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="AreaCodePosAddr">  <!-- Area Code of Recipient’s Correspondence Address -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="1" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="PhoneNum">  <!-- Recipient’s Telephone no. -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="15" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Capacity">  <!-- Capacity in which Engaged -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="40" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="StartDateOfService">  <!-- Start Date of Service Rendered -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="8" />
                                        <xs:pattern value="[0-9]*" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="EndDateOfService">  <!-- End Date of Service Rendered -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="8" />
                                        <xs:pattern value="[0-9]*" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="AmtOfType1" type="amount" />  <!-- Amount of Type 1 Subcontracting fees -->
                            <xs:element name="AmtOfType2" type="amount" />  <!-- Amount of Type 2 Commission income -->
                            <xs:element name="AmtOfType3" type="amount" />  <!-- Amount of Type 3 Writer’s / Contributor’s fee -->
                            <xs:element name="AmtOfArtistFee" type="amount" />  <!-- Amount of Artiste’s fees -->
                            <xs:element name="AmtOfCopyright" type="amount" />  <!-- Amount of Copyright/Royalties -->
                            <xs:element name="AmtOfConsultFee" type="amount" />  <!-- Amount of Consultancy/Management fees -->
                            <xs:element name="NatureOtherInc1">  <!-- Nature of 1st Other income -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="35" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="AmtOfOtherInc1" type="amount" />  <!-- Amount of 1st Other income -->
                            <xs:element name="NatureOtherInc2">  <!-- Nature of 1st Other income -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="35" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="AmtOfOtherInc2" type="amount" />  <!-- Amount of 1st Other income -->
                            <xs:element name="TotalIncome">  <!-- Total Income -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1" />
                                        <xs:maxLength value="9" />
                                        <xs:pattern value="[0-9]*" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="IndOfSumWithheld">  <!-- Indicator of sum withheld to settle tax due by recipient -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="0" />
                                        <xs:enumeration value="1" />
                                        </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="AmtOfSumWithheld" type="amount" />  <!-- Amount of sum withheld -->
                            <xs:element name="IndOfRemark">  <!-- Indicator of sum withheld to settle tax due by recipient -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="0" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Remarks">  <!-- Remarks -->
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="60" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="amount">
        <xs:restriction base="xs:string">
            <xs:maxLength value="9" />
            <xs:pattern value="[0-9]*" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== laputafish/yoovapi55/source/xml_scheme/ir56m.xml
<?xml version="1.0" encoding="UTF-8"?>
<IR56M xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='ir56m.xsd'>
	<Section>6A1</Section>
	<ERN>01234561</ERN>
	<AssYr>2014</AssYr>
	<SubDate>20140420</SubDate>
	<PayerName>ABCD COMPANY</PayerName>
	<Designation>Partner</Designation>
	<NoRecordBatch>00002</NoRecordBatch>
	<TotIncomeBatch>250000</TotIncomeBatch>
	<Recipient>
		<SheetNo>900001</SheetNo>
		<ComRecNameEng />
		<ComRecNameChi />
		<ComRecBRN />
		<HKID>A1144557</HKID>
		<NameInEnglish>AUYEUNG, TAI MAN PETER</NameInEnglish>
		<NameInChinese>歐陽大文</NameInChinese>
		<Sex>M</Sex>
		<MaritalStatus>2</MaritalStatus>
		<SpouseName>WONG, MEI MEI</SpouseName>
		<SpouseHKID />
		<SpousePpNum>A4567891</SpousePpNum>
		<PosAddr />
		<AreaCodePosAddr />
		<PhoneNum />
		<Capacity />
		<StartDateOfService>20130401</StartDateOfService>
		<EndDateOfService>20140331</EndDateOfService>
		<AmtOfType1>150000</AmtOfType1>
		<AmtOfType2>0</AmtOfType2>
		<AmtOfType3>0</AmtOfType3>
		<AmtOfArtistFee>0</AmtOfArtistFee>
		<AmtOfCopyright>0</AmtOfCopyright>
		<AmtOfConsultFee>0</AmtOfConsultFee>
		<NatureOtherInc1 />
		<AmtOfOtherInc1>0</AmtOfOtherInc1>
		<NatureOtherInc2 />
		<AmtOfOtherInc2>0</AmtOfOtherInc2>
		<TotalIncome>150000</TotalIncome>
		<IndOfSumWithheld>0</IndOfSumWithheld>
		<AmtOfSumWithheld>0</AmtOfSumWithheld>
		<IndOfRemark>0</IndOfRemark>
		<Remarks />
	</Recipient>
	<Recipient>
		<SheetNo>900002</SheetNo>
		<ComRecNameEng />
		<ComRecNameChi />
		<ComRecBRN />
		<HKID>B2044557</HKID>
		<NameInEnglish>CHAN, WAI KWONG</NameInEnglish>
		<NameInChinese />
		<Sex>M</Sex>
		<MaritalStatus>2</MaritalStatus>
		<SpouseName />
		<SpouseHKID />
		<SpousePpNum />
		<PosAddr />
		<AreaCodePosAddr />
		<PhoneNum />
		<Capacity />
		<StartDateOfService>20130401</StartDateOfService>
		<EndDateOfService>20140331</EndDateOfService>
		<AmtOfType1>100000</AmtOfType1>
		<AmtOfType2>0</AmtOfType2>
		<AmtOfType3>0</AmtOfType3>
		<AmtOfArtistFee>0</AmtOfArtistFee>
		<AmtOfCopyright>0</AmtOfCopyright>
		<AmtOfConsultFee>0</AmtOfConsultFee>
		<NatureOtherInc1 />
		<AmtOfOtherInc1>0</AmtOfOtherInc1>
		<NatureOtherInc2 />
		<AmtOfOtherInc2>0</AmtOfOtherInc2>
		<TotalIncome>100000</TotalIncome>
		<IndOfSumWithheld>0</IndOfSumWithheld>
		<AmtOfSumWithheld>0</AmtOfSumWithheld>
		<IndOfRemark>0</IndOfRemark>
		<Remarks />
	</Recipient>
</IR56M>
